name: CI

on: 
  pull_request:
      branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      run: echo Hello, world!
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
